options:
  san-ip:
    type: string
    description: "Management VIP address of the Pure Storage FlashArray"
  pure-api-token:
    type: string
    description: "API token for FlashArray access"
  protocol:
    type: string
    default: iscsi
    description: "SAN protocol to use. Choose between iscsi or fc."
