options:
  driver-source:
    type: string
    default:
    description: |
      Optional configuration to support use of additional sources such as:
        - ppa:myteam/ppa
        - cloud:trusty-proposed/kilo
        - http://my.archive.com/ubuntu main
      The last option should be used in conjunction with the key configuration
      option.
  driver-key:
    type: string
    default:
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
  debug:
    default: !!bool false
    type: boolean
    description: Enable debug logging
  verbose:
    default: !!bool false
    type: boolean
    description: Enable verbose logging
  use-syslog:
    type: boolean
    default: !!bool false
    description: |
      Setting this to True will allow supporting services to log to syslog.
  use-internal-endpoints:
    type: boolean
    default: !!bool false
    description: |
      Openstack mostly defaults to using public endpoints for
      internal communication between services. If set to True this option
      will configure services to use internal endpoints where possible.
  san-ip:
    type: string
    description: "Management VIP address of the Pure Storage FlashArray"
    default:
  pure-api-token:
    type: string
    description: "API token for FlashArray access"
    default:
  protocol:
    type: string
    default: iscsi
    description: SAN protocol to use. Choose between iscsi or fc.
  volume-backend-name:
    type: string
    description: Service name to present to Cinder
    default: !!null ""
